//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class create
    {

        /// <summary>
        /// form2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox username;
        protected global::System.Web.UI.WebControls.TextBox firstname;
        protected global::System.Web.UI.WebControls.TextBox surname;
        protected global::System.Web.UI.WebControls.TextBox email;
        protected global::System.Web.UI.WebControls.TextBox pass;
        protected global::System.Web.UI.WebControls.TextBox city;
        protected global::System.Web.UI.WebControls.TextBox country;
        protected global::System.Web.UI.WebControls.Button gumb;

    }
}
