//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class editprofile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form3;

        protected global::System.Web.UI.WebControls.TextBox firstname;
        protected global::System.Web.UI.WebControls.TextBox surname;
        protected global::System.Web.UI.WebControls.TextBox email;
        protected global::System.Web.UI.WebControls.TextBox telephone;
        protected global::System.Web.UI.WebControls.TextBox city;
        protected global::System.Web.UI.WebControls.TextBox country;
        protected global::System.Web.UI.WebControls.TextBox datepicker;
        protected global::System.Web.UI.WebControls.Button gumb;
    }
}
