//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    public partial class Index
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form4;

        protected global::System.Web.UI.WebControls.TextBox user;
        protected global::System.Web.UI.WebControls.TextBox pasvd;
        protected global::System.Web.UI.WebControls.Button gumb;
    }
}
